services:
  - type: web
    name: fakeageanalysis
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/status
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
